// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3XYCDpZ73chgHb_rw0Xitno8Z7E7mOXM',
    appId: '1:813628768784:web:e88500e0086c08cb6f4095',
    messagingSenderId: '813628768784',
    projectId: 'mynotes-shashwat-raj',
    authDomain: 'mynotes-shashwat-raj.firebaseapp.com',
    storageBucket: 'mynotes-shashwat-raj.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQFow0OJMwj8bDa59uUAoOEQIY5r9FUbo',
    appId: '1:813628768784:android:1242a2373ed3e4c76f4095',
    messagingSenderId: '813628768784',
    projectId: 'mynotes-shashwat-raj',
    storageBucket: 'mynotes-shashwat-raj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArwjyVYNBb-006MCZY3FuPmVcQanLjOLI',
    appId: '1:813628768784:ios:c4306bfe1754058f6f4095',
    messagingSenderId: '813628768784',
    projectId: 'mynotes-shashwat-raj',
    storageBucket: 'mynotes-shashwat-raj.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArwjyVYNBb-006MCZY3FuPmVcQanLjOLI',
    appId: '1:813628768784:ios:c4306bfe1754058f6f4095',
    messagingSenderId: '813628768784',
    projectId: 'mynotes-shashwat-raj',
    storageBucket: 'mynotes-shashwat-raj.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3XYCDpZ73chgHb_rw0Xitno8Z7E7mOXM',
    appId: '1:813628768784:web:4414549ff59f3fcb6f4095',
    messagingSenderId: '813628768784',
    projectId: 'mynotes-shashwat-raj',
    authDomain: 'mynotes-shashwat-raj.firebaseapp.com',
    storageBucket: 'mynotes-shashwat-raj.firebasestorage.app',
  );
}
